repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^backend/alembic/
      - id: end-of-file-fixer
        exclude: ^backend/alembic/
      - id: check-yaml
        exclude: ^backend/alembic/
      - id: check-added-large-files
        exclude: ^backend/alembic/

  # - repo: https://github.com/psf/black
  #   rev: 24.2.0
  #   hooks:
  #     - id: black
  #       args: [--line-length=120]

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8

  # For type checking
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy

  # # For import sorting
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.13.2
  #   hooks:
  #     - id: isort
