name: mployee
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5900:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
      - "8000:8000" # fastapi
    env_file:
      - .env
    volumes:
      - ./backend:/home/mployee/backend
      - ./image:/home/mployee/image
      - ./.env:/home/mployee/.env
